config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users
  resources :articles, only: [:index, :new, :create]

  get 'users/new', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :confirmable,
         :database_authenticatable,
         :registerable,
         :recoverable, 
         :rememberable,
         :trackable, 
         :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: :index
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_user.articles.new
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
            @user = User.new
  end
  def create
            @user = User.new(user_params)
            if @user.save
                        redirect_to @user, notice: "Usuário foi criado com sucesso!"
                        #tire o método de comentário quando criar o helper.
                        #Usuário depois de cadastrar-se acessa o sistema automaticamente
                        #sign_in(@user)
            else
  render action: :new
            end
  end

  private
  def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.erb
<h1>Hello, Rails!</h1>

app/views/layouts/_account_links.html.erb
<% if user_signed_in? %>
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    <%= currrent_user.email %>
  </button>
  <ul class="dropdown-menu">
    <li>
      <%= link_to 'Edit User', edit_user_registration_path, class: 'dropdown-item' %>
    </li>
    <li><hr class="dropdown-divider"></li>
    <li>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
    </li>
  </ul>
</div>
<% else %>
      <%= link_to 'Sign in', new_user_session_path, method: :delete, class: 'linkk-secondary' %>
      <%= link_to 'Sign up', new_user_registration_path, method: :delete, class: 'nav-item' %>
<% end%>

app/views/layouts/_topnavbar.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "MyApp", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link text-primary" %>
        </li>
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link text-danger" %>
        </li>
        <!-- Add more navigation links as needed -->
      </ul>
    </div>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <%= render 'layouts/account_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
            <% if @user.errors.any? %>
            <div id="error_explanation">
                        <div class="alert-error">
                                   O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
                        </div>
                        <ul>
                                   <% @user.errors.full_messages.each do |msg| %>
                                   <li><%= msg %></li>
                                   <% end %>
                        </ul>
            </div>
  <% end %>
            <div class="field">
                        <%= f.label :name %>
                        <%= f.text_field :name %>
            </div>
            <div class="field">
                        <%= f.label :email %>
                        <%= f.email_field :email %>
            </div>
            <div class="field">
                        <%= f.label :password %>
                        <%= f.password_field :password %>
            </div>
            <div class="field">
                        <%= f.label :password_confirmation %>
                        <%= f.password_field :password_confirmation %>
            </div>
            <div class="actions">
                        <%= f.submit "Cadastrar"%>
            </div>
<% end %>